// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: src/proto/judge_grpc_service/judge_grpc_service.proto

package judge_grpc_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JudgeGrpcService_Submit_FullMethodName = "/judge_grpc_service.JudgeGrpcService/Submit"
)

// JudgeGrpcServiceClient is the client API for JudgeGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JudgeGrpcServiceClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
}

type judgeGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeGrpcServiceClient(cc grpc.ClientConnInterface) JudgeGrpcServiceClient {
	return &judgeGrpcServiceClient{cc}
}

func (c *judgeGrpcServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, JudgeGrpcService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeGrpcServiceServer is the server API for JudgeGrpcService service.
// All implementations must embed UnimplementedJudgeGrpcServiceServer
// for forward compatibility.
type JudgeGrpcServiceServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	mustEmbedUnimplementedJudgeGrpcServiceServer()
}

// UnimplementedJudgeGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJudgeGrpcServiceServer struct{}

func (UnimplementedJudgeGrpcServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedJudgeGrpcServiceServer) mustEmbedUnimplementedJudgeGrpcServiceServer() {}
func (UnimplementedJudgeGrpcServiceServer) testEmbeddedByValue()                          {}

// UnsafeJudgeGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeGrpcServiceServer will
// result in compilation errors.
type UnsafeJudgeGrpcServiceServer interface {
	mustEmbedUnimplementedJudgeGrpcServiceServer()
}

func RegisterJudgeGrpcServiceServer(s grpc.ServiceRegistrar, srv JudgeGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedJudgeGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JudgeGrpcService_ServiceDesc, srv)
}

func _JudgeGrpcService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeGrpcServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeGrpcService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeGrpcServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeGrpcService_ServiceDesc is the grpc.ServiceDesc for JudgeGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "judge_grpc_service.JudgeGrpcService",
	HandlerType: (*JudgeGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _JudgeGrpcService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/judge_grpc_service/judge_grpc_service.proto",
}
